version: '3.8'

services:
  api:
    build: .
    container_name: aws-security-audit-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=info
    restart: unless-stopped
    command: python main.py
