# Secrets template for Streamlit Cloud
# Copy this to Streamlit Cloud Secrets Management

# Add your secrets here if needed
# For now, this app doesn't require secrets
# But this file serves as a template

[general]
app_name = "AWS Security Audit Tool"
version = "1.0.0"
